[include_app]
    [include_app.ubuntu_wsl]
        aws_cli = true
        chezmoi = true
        clipboard_project = true
        curl = true
        direnv = true
        fzf = true
        git = true
        gopass = true
        kubectl = true
        lsd = true
        mintty = false
        navi = true
        ripgrep = true
        ssh = true
        wget = true
        xclip = true # Used copy and paste alias
        zoxide = true
