[[snippets]]
  description = "Add last command to pet"
  command = "pet new \"!!\""
  tag = ["pet"]
  output = ""

[[snippets]]
  description = "Copy to clipboard"
  command = "pet search | pbcopy"
  tag = ["pet"]
  output = ""

[[snippets]]
  description = "S3 check if bucket versioning is on"
  command = "aws s3api get-bucket-versioning --bucket <bucket=$BUCKET_NAME>"
  tag = ["aws"]
  output = ""
  #  aws s3api list-objects-v2 --bucket $BUCKET_NAME

[[snippets]]
  description = "Execute bash to existing container and enter to root"
  command = "docker exec -it ubuntu /bin/bash"
  tag = ["docker"]
  output = ""

# source: https://forums.docker.com/t/restart-docker-from-command-line/9420/7
[[snippets]]
  description = "Stop Docker in Mac gracefully"
  command = "test -z \"$(docker ps -q 2>/dev/null)\" && osascript -e 'quit app \"Docker\"'"
  tag = ["docker", "mac"]
  output = ""

[[snippets]]
  description = "Start Docker in Mac"
  command = "open --background -a Docker"
  tag = ["docker", "mac"]
  output = ""

[[snippets]]
  description = "Display all (active and inactive) containers"
  command = "docker ps -a"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Display images"
  command = "docker images "
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Run container as daemon"
  command = "docker run -d -i -t --name ubuntu ubuntu"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Run container"
  command = "docker run -it ubuntu bash"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Pull images"
  command = "docker pull alphine"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Inspect image"
  command = "docker inspect <container>"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Find untagged images"
  command = "docker images --filter \"dangling=true\""
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "List images created after container created"
  command = "docker images --filter since=<container>"
  output = ""

[[snippets]]
  description = "List images created prior to container created"
  command = "docker images --filter before=<container>"
  output = ""

[[snippets]]
  description = "Remove untagged images"
  command = "docker rmi $(docker images --filter \"dangling=true\" -q)"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Stop all containers"
  command = "docker stop $(docker ps -q)"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Remove all running containers"
  command = "docker rm $(docker ps -a -q) # Destructive"
  tag = ["docker"]
  output = ""

[[snippets]]
  description = "Mac reset audio"
  command = "sudo killall coreaudiod"
  tag = ["mac"]
  output = ""

[[snippets]]
  description = "Figlet and Boxes (Pound)"
  command = "figlet -f big \"<message>\" | boxes -d pound-cmt -pa2l2 -a hcvc | sed -e 's/^[ \t]*//' -e '$s/$/ <message>/'"
  tag = ["boxes", "figlet"]
  output = ""

[[snippets]]
  description = "Multi line"
  command = "This string\nhas ' a quote character\nand more than\none newline\nin it."
  output = ""
