[include_app]
    [include_app.darwin]
        aws_cli = true
        chezmoi = true
        clipboard_project = true
        curl = true
        direnv = true
        fzf = true
        git = true
        gopass = true
        lsd = true
        mintty = false
        navi = true
        ripgrep = true
        ssh = true
        wget = true
        xclip = false # Not use
        zoxide = true
