[include_app]
    [include_app.darwin]
        chezmoi = true
        curl = true
        direnv = true
        git = true
        gopass = true
        lsd = true
        mintty = false
        ripgrep = true
        ssh = true
        wget = true
        zoxide = true
