# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Naming rule
# 1.  dash to delimit subcommand
# 2.  Upper case to differentiate word
# 3.  dash to delimite switch

# To generate box
#  boxes -d shell -p a1l2
#  Example: echo "Docker" | boxes -d pound-cmt -i none


secure_input_notification: false

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ":time"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%H:%M"

  - trigger: ":isodate"
    replace: "{{isodate}}"
    vars:
      - name: isodate
        type: date
        params:
          format: "%Y-%m-%dT%H:%M:%S%z"

  - trigger: ":uuid,"
    replace: "{{myuuid}}"
    vars:
      - name: myuuid
        type: shell
        params:
           cmd: "uuidgen | tr 'A-Z' 'a-z'"

  - trigger: ":uuid0,"
    replace: "{{myuuid}}"
    vars:
      - name: myuuid
        type: shell
        params:
           cmd: "uuidgen | sed s/[a-zA-Z0-9]/0/g"

  - trigger: ":uuid1,"
    replace: "{{myuuid}}"
    vars:
      - name: myuuid
        type: shell
        params:
           cmd: "uuidgen | sed s/[a-zA-Z0-9]/1/g"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  #
  #
  #       __          _______
  #      /\ \        / / ____|
  #     /  \ \  /\  / / (___
  #    / /\ \ \/  \/ / \___ \
  #   / ____ \  /\  /  ____) |
  #  /_/    \_\/  \/  |_____/
  #
  #
  #
  # AWS
  - trigger: ":aws-cf,"
    replace: "aws cloudformation "

  - trigger: ":aws-cf-ds,"
    replace: "aws cloudformation describe-stacks "

  - trigger: ":aws-cf-ec,"
    replace: "aws cloudformation estimate-cost "

  - trigger: ":aws-cf-cs,"
    replace: "aws cloudformation create-stack --stack-name   --template-body file://  --paramaters ParameterKey= ,Parameter-Value= "

  - trigger: ":awsp-p,"
    replace: "--paramaters ParameterKey=$|$,Parameter-Value="

  - trigger: ":awspv-p,"
    replace: "ParameterKey=$|$,Parameter-Value="

  - trigger: ":aws-cf-vt,"
    replace: "aws cloudformation validate-template --template-body file://$|$"

# aws estimate cost, create stack, pv, pk,

###########
#         #
#  Docker #
#         #
###########
# Moved to dcoker.yml

  #
  #
  #   _____             _                _____
  #  |  __ \           | |              / ____|
  #  | |  | | ___   ___| | _____ _ __  | |     ___  _ __ ___  _ __   ___  ___  ___
  #  | |  | |/ _ \ / __| |/ / _ \ '__| | |    / _ \| '_ ` _ \| '_ \ / _ \/ __|/ _ \
  #  | |__| | (_) | (__|   <  __/ |    | |___| (_) | | | | | | |_) | (_) \__ \  __/
  #  |_____/ \___/ \___|_|\_\___|_|     \_____\___/|_| |_| |_| .__/ \___/|___/\___|
  #                                                          | |
  #                                                          |_|
  #
  # Docker Compose
  - trigger: ":dc-d,"
    replace: "docker-compose down $|$"

  - trigger: ":dc-ps,"
    replace: "docker-compose ps $|$"

  - trigger: ":dc-v,"
    replace: "docker-compose version $|$"

  - trigger: ":dc-u,"
    replace: "docker-compose up --remove-orphans $|$"

  - trigger: ":dc-uD,"
    replace: "docker-compose up --detach $|$"

  - trigger: ":dn-rg,"
    replace: reportgenerator "-reports:coverage/lcov.info" "-targetdir:coverage/reports" "-reporttypes:Html;HtmlSummary" $|$

  - trigger: ":dn-t,"
    replace: "dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=..coverage/lcov.info $|$"

  - trigger: ":dn-wr,"
    replace: "dotnet watch run --project $|$"

  # - trigger: ":dn-wt,"
  #   replace: "dotnet watch test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../coverage/lcov.info --project $|$"
  - trigger: ":dn-wt,"
    replace: |
      find . -name '*.sln' -maxdepth 1 -print -quit | xargs -I {} \
      dotnet watch test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../coverage/lcov.info \
      --project {} \

  - trigger: ":dn-wb,"
    replace: "dotnet watch build --project $|$"

  # https://docs.microsoft.com/en-us/ef/core/cli/dotnet
  # EF list migration
  - trigger: ":dn-ef-ml,"
    replace: "dotnet ef migrations list $|$"

  - trigger: ":dn-ef-ci,"
    replace: "dotnet ef dbcontext info"

  - trigger: ":dn-ef-cl,"
    replace: "dotnet ef dbcontext list"

  # DROP database and migration
  - trigger: ":dn-ef-DNM,"
    replace: "dotnet ef database drop -f -v && dotnet ef database update"

  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'https://api.ipify.org'"

  # pet script
  - trigger: ";pet,"
    # force_clipboard: true
    replace: |
              [[snippets]]
                description = "$|$"
                command = "{{clipboard}}"
                tag = [""]
                output = ""
    vars:
      - name: "clipboard"
        type: "clipboard"

  # markdown
  - trigger: ";md-title,"
    # Note: Need to TBD to fix dash line parsing issue.
    replace: |
              ---
              title: "$|$"
              keywords:
                - TBD

              ...
    vars:
      - name: "clipboard"
        type: "clipboard"

  #
  #
  #                   _
  #                  | |
  #    ___ _   _ _ __| |
  #   / __| | | | '__| |
  #  | (__| |_| | |  | |
  #   \___|\__,_|_|  |_|
  #
  #
  #
  # curl
  - trigger: ":curl-Pon,"
    replace: "export http_proxy=localhost:8080;export https_proxy=localhost:8080"

  - trigger: ":curl-Poff,"
    replace: "unset http_proxy; unset https_proxy"

  - trigger: ":g-c-an,"
    replace: "git commit --amend --no-edit"

  # TO DELETE below.
  - trigger: "rrgs"
    force_clipboard: true
    replace: "group_by($|$) %>%\n    summarise()\n"

  - trigger: ":greet"
    replace: "Hey $0$, how are you?\nIt's been a while!"
    passive_only: true

  - trigger: ":reversed"
    replace: "Reversed {{myshell}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"
      - name: myshell
        type: shell
        params:
          cmd: "echo $ESPANSO_MYTIME | rev"
