[include_app]
    [include_app.windows]
        aws_cli = true
        bash = true
        chezmoi = true
        clipboard_project = false # TODO: Integrate to windows
        curl = true
        direnv = false # No windows support
        dotnet = true
        espanso = true
        git = true
        fastfetch = false # TODO: Integrate to windows
        fzf = true
        gnupg = false # TODO: Integrate to windows
        gopass = false # TODO: Integrate to windows
        homebrew = false # Not use
        kubectl = false # TODO: Integrate to windows
        lsd = false # TODO: Integrate to windows
        mintty = true
        nano = true
        navi = false # TODO: Integrate to windows
        python = false # TODO: Integrate to windows
        ripgrep = true
        rust = false # TODO: Integrate to windows
        ssh = true
        volta = false # TODO: Integrate to windows
        wget = true
        xclip = false # Not use
        zoxide = true
