[include_app]
    [include_app.windows]
        aws_cli = true
        chezmoi = true
        clipboard_project = false # TODO: Integrate to windows
        curl = true
        direnv = false # No windows support
        espanso = true
        git = true
        fzf = true
        gnupg = false # TODO: Integrate to windows
        gopass = false # TODO: Integrate to windows
        kubectl = false # TODO: Integrate to windows
        lsd = false # TODO: Integrate to windows
        mintty = true
        navi = false # TODO: Integrate to windows
        ripgrep = true
        ssh = true
        wget = true
        xclip = false # Not use
        zoxide = true
